#!/bin/bash
# SOURCE FILE: setup-client
#
# PROGRAM: client setup script
#
# Last Modified: October 6, 2014
#                Nov 17, 2014
#
#
# Changelog:    - Changed scapy install to pip
#
# DESIGNER: Slade Solobay & Zach Smoroden
#
# PROGRAMMER: Slade Solobay & Zach Smoroden
#
# NOTES: This script will setup and install all the libraries required to run the client.



yum install libpcap-devel -y
yum install python-devel -y
yum install python-pip -y
pip install scapy -y
pip install netifaces